### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by b1gcat** [L-codes/pwcrack-framework#11]
师傅帮忙看看  。 之前可以用升级不行了。
```
pwcrack-framework/lib/passwd.rb:180:in `block in find_hash_type': undefined local variable or method `_1' for CLI:Module (NameError)
	from /Users/b1gcat/Desktop/hack/password/pwcrack-framework/lib/passwd.rb:180:in `each_char'
	from /Users/b1gcat/Desktop/hack/password/pwcrack-framework/lib/passwd.rb:180:in `each'
	from /Users/b1gcat/Desktop/hack/password/pwcrack-framework/lib/passwd.rb:180:in `filter'
	from /Users/b1gcat/Desktop/hack/password/pwcrack-framework/lib/passwd.rb:180:in `find_hash_type'
	from /Users/b1gcat/Desktop/hack/password/pwcrack-framework/lib/passwd.rb:36:in `passwd_analysis'
	from /Users/b1gcat/Desktop/hack/password/pwcrack-framework/lib/cli.rb:62:in `commandline!'
	from ./pwcrack:24:in `<main>'
```

**Comment by L-codes** [comment]
现在需要 更新到 ruby 3.1或以上才能运行

**Comment by b1gcat** [comment]
升级到3.0可以了 谢谢师傅
