### ISSUE TITLE
windows下安装rjb失败

### ISSUE THREAD

**Issue by winezer0** [L-codes/pwcrack-framework#28]
环境：

```
windows下 ruby31

rubyinstaller-devkit-3.1.4-1-x64.exe

pwcrack-framework 最新版 20230514下载

echo %JAVA_HOME%
C:\Program_Base\jdk8
```

问题：

bundle install 安装rjb失败 

![image](https://github.com/L-codes/pwcrack-framework/assets/46115146/008fd70a-a959-460c-8c26-2454433507aa)

错误详情：
```
Installing rjb 1.6.7 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Program_Base/Ruby31/lib/ruby/gems/3.1.0/gems/rjb-1.6.7/ext
C:/Program_Base/Ruby31/bin/ruby.exe -I C:/Program_Base/Ruby31/lib/ruby/3.1.0
extconf.rb
checking for javah... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Program_Base/Ruby31/bin/$(RUBY_BASE_NAME)
extconf.rb:83:in `<main>': invalid byte sequence in UTF-8 (ArgumentError)

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

C:/Program_Base/Ruby31/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/rjb-1.6.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
C:/Program_Base/Ruby31/lib/ruby/gems/3.1.0/gems/rjb-1.6.7 for inspection.
Results logged to
C:/Program_Base/Ruby31/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/rjb-1.6.7/gem_make.out

  C:/Program_Base/Ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:102:in `run'
C:/Program_Base/Ruby31/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:28:in
`build'
C:/Program_Base/Ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:171:in
`build_extension'
C:/Program_Base/Ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:205:in `block in
build_extensions'
  C:/Program_Base/Ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:202:in `each'
C:/Program_Base/Ruby31/lib/ruby/3.1.0/rubygems/ext/builder.rb:202:in
`build_extensions'
C:/Program_Base/Ruby31/lib/ruby/3.1.0/rubygems/installer.rb:843:in
`build_extensions'
C:/Users/WINDOWS/.local/share/gem/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/rubygems_gem_installer.rb:72:in
`build_extensions'
C:/Users/WINDOWS/.local/share/gem/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
C:/Users/WINDOWS/.local/share/gem/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/source/rubygems.rb:200:in
`install'
C:/Users/WINDOWS/.local/share/gem/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/installer/gem_installer.rb:54:in `install'
C:/Users/WINDOWS/.local/share/gem/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
C:/Users/WINDOWS/.local/share/gem/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/installer/parallel_installer.rb:155:in
`do_install'
C:/Users/WINDOWS/.local/share/gem/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/installer/parallel_installer.rb:146:in
`block in worker_pool'
C:/Users/WINDOWS/.local/share/gem/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/worker.rb:62:in
`apply_func'
C:/Users/WINDOWS/.local/share/gem/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/worker.rb:57:in
`block in process_queue'
C:/Users/WINDOWS/.local/share/gem/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/worker.rb:54:in
`loop'
C:/Users/WINDOWS/.local/share/gem/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/worker.rb:54:in
`process_queue'
C:/Users/WINDOWS/.local/share/gem/ruby/3.1.0/gems/bundler-2.4.6/lib/bundler/worker.rb:90:in
`block (2 levels) in create_threads'

An error occurred while installing rjb (1.6.7), and Bundler cannot
continue.

In Gemfile:
  rjb

```

**Comment by L-codes** [comment]
我看了一下 是 rjb 这里的问题 [ext/extconf.rb](https://github.com/arton/rjb/blob/70d90584726dbf90e92cad37e26db8d696953831/ext/extconf.rb#LL83C17-L83C30)，应该是 `javah -version` 含有中文了，可以单独执行 `javah -version`看看返回结果吗？

**Comment by winezer0** [comment]
是回显了
λ javah -version
javah版本 "1.8.0_261"

**Comment by winezer0** [comment]
测试发现chcp 65001还是不行，javah结果乱码了

**Comment by L-codes** [comment]
https://github.com/arton/rjb/blob/70d90584726dbf90e92cad37e26db8d696953831/ext/extconf.rb#LL83C17-L83C30
那这里的代码，你可以改成下面这样，或者直接把版本写死，不然要提issue给rjb作者了：
```ruby
hversion = (`javah -version`.b =~ /\d+\.\d+\.\d+/ )  ? $& : nil
```

或者改英文编码试试 `chcp 437`

**Comment by winezer0** [comment]
尝试了修改界面编码，没啥用.
java8 java7 java6 的javah都有个中文
![image](https://github.com/L-codes/pwcrack-framework/assets/46115146/38942187-b330-4ac9-9b53-4362e2409b25)

尝试修改gems下的rb代码
hversion = (`javah -version` =~ /\d+\.\d+\.\d+/ )  ? $& : nil

发现bundle  install的时候会重新下载，不会用本地的。

尝试修改cache里面的rjb.gem , gem install xxx.gem -l 安装本地gems

发现里面都是gz后缀的压缩，windows上无法操作

看能不能修改一下这个

**Comment by L-codes** [comment]
你可以自己修改打包安装
```ruby
git clone https://github.com/arton/rjb
cd rjb
# 修改好代码后
gem build rjb.gemspec;
gem install *.gem
```

**Comment by winezer0** [comment]
感谢，学到了，我这就试试

**Comment by winezer0** [comment]
临时解决方案:
修改windows语言

![image](https://github.com/L-codes/pwcrack-framework/assets/46115146/92358049-943d-45ba-b252-db15e7081cd9)

![image](https://github.com/L-codes/pwcrack-framework/assets/46115146/2217c51b-e731-4d0b-b333-20a8f4ec4da3)

![image](https://github.com/L-codes/pwcrack-framework/assets/46115146/ac8cec3b-4e7a-4973-8b0d-5b804f9f63d8)

**Comment by winezer0** [comment]
重新还原语言后一切正常

![image](https://github.com/L-codes/pwcrack-framework/assets/46115146/e171dd2e-6ff9-4799-a4ac-b83d37adb813)
