### ISSUE TITLE
运行./pwcrack错误

### ISSUE THREAD

**Issue by 200210xsb** [L-codes/pwcrack-framework#36]
运行./pwcrack banner
显示/usr/bin/env: invalid option -- 'S'
Try '/usr/bin/env --help' for more information.错误

**Comment by 200210xsb** [comment]
ruby ./pwcrack

**Comment by L-codes** [comment]
请问 `bash --version` 的版本是?

**Comment by XZ1314XZ** [comment]
E:\DevProject\RubyProject\pwcrack-framework>ruby ./pwcrack
E:/DevProject/RubyProject/pwcrack-framework/external/java_ext/java_ext.rb:13:in `add_jar': bignum too big to convert into `unsigned long' (RangeError)
        from E:/DevProject/RubyProject/pwcrack-framework/external/java_ext/java_ext.rb:13:in `block in <top (required)>'        from E:/DevProject/RubyProject/pwcrack-framework/external/java_ext/java_ext.rb:12:in `each'
        from E:/DevProject/RubyProject/pwcrack-framework/external/java_ext/java_ext.rb:12:in `<top (required)>'
        from E:/DevProject/RubyProject/pwcrack-framework/lib/env.rb:19:in `load'
        from E:/DevProject/RubyProject/pwcrack-framework/lib/env.rb:19:in `block in <top (required)>'
        from E:/DevProject/RubyProject/pwcrack-framework/lib/env.rb:17:in `each_child'
        from E:/DevProject/RubyProject/pwcrack-framework/lib/env.rb:17:in `<top (required)>'
        from ./pwcrack:13:in `require_relative'
        from ./pwcrack:13:in `<main>'

**Comment by XZ1314XZ** [comment]
![1697144269902](https://i2.100024.xyz/2023/10/13/7kdgyt.webp)

**Comment by L-codes** [comment]
@XZ1314XZ 请问你的ruby版本和pwcrack版本是？

**Comment by XZ1314XZ** [comment]
> @XZ1314XZ 请问你的ruby版本和pwcrack版本是？

pwcrack是昨晚刚拉的最新版
ruby是ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x64-mingw-ucrt]

**Comment by L-codes** [comment]
@XZ1314XZ 建议试试升级ruby 到3.2+试试 ，如还不行 需要到 [rjb](https://github.com/arton/rjb)上提交issue了

**Comment by winezer0** [comment]
使用windows + jdk 11+ 环境也发现了这个转换问题。

使用 jdk8没有这个转换问题
